/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wQNRfFALoZQSPmYtsM69zT

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantspPre1MV5344S } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PPre1mV5344S/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantspPre1MV5344S
});
